/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_net_xyd_videoaudiodemo_convert_LameConvert */

#ifndef _Included_cn_net_xyd_videoaudiodemo_convert_LameConvert
#define _Included_cn_net_xyd_videoaudiodemo_convert_LameConvert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_net_xyd_videoaudiodemo_convert_LameConvert
 * Method:    convertmp3
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_net_xyd_videoaudiodemo_convert_LameConvert_convertmp3
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     cn_net_xyd_videoaudiodemo_convert_LameConvert
 * Method:    getLameVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_cn_net_xyd_videoaudiodemo_convert_LameConvert_getLameVersion
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
